---
kind: pipeline
name: test

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:5.10.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: node:8-alpine
  commands: ["npm install"]

- name: test
  image: node:8-alpine
  commands: ["npm test"]

- name: publish
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]

---
kind: signature
hmac: 738c9b2788da65ba7e70c0803ada199c856035c470a28fa25b4e47874f9de798

...
